#!/bin/bash


convertdir(){
  local dir=$1
  local targdir=$2
  echo "dir=$dir, target dir=$targdir"
  
  
  for file in `ls -1 $dir`;
  do
    check=$dir"/"$file
  
    local target=""
    local header=`echo $file | grep "\.h"`
    local cfile=`echo $file | grep "\.c"`
    local both=`echo "$header$cfile" `
  
    if [[ -z $both ]]
    then
    	echo -n
    elif [[ -z $cfile ]]
    then
      target=`basename $file ".h"`
      touch $targdir/log.txt
      #echo "Converting $dir/$file into $targdir/$file"
      echo "" >> $targdir/log.txt
      echo "$file" >> $targdir/log.txt
      ./precompiler/precompile $dir/$file $targdir/$file -x ./gsl-conffiles/mpieee.xml >> $targdir/log.txt 2>&1
      echo "precompiler/precompile $dir/$file $targdir/$file -x gsl-conffiles/mpieee.xml"
    elif [[ -z $header ]]
    then
      target=`basename $file ".c"`

      #echo "Converting $dir/$file into $targdir/$file"
      echo "" >> $targdir"/"log.txt
      echo "$file" >> $targdir"/"log.txt
      ./precompiler/precompile $dir/$file $targdir/$file -x ./gsl-conffiles/mpieee.xml >> $targdir/log.txt 2>&1
      echo "precompiler/precompile $dir/$file $targdir/$file -x gsl-conffiles/mpieee.xml"
    fi
  done
}

convertdir $1 $2

