char *str = "\n====================================================================================\n"
            "\n               >>>   Example 4b - Talbot Suite DE   <<<\n"
            "\n         Application of Talbot's method to solve the PDE equation\n"
            "\n\t\t\tu_tt (x,t) = u_xx (x,t),         0 < x < L,  t>0\n"
            "\n\twith conditions:"
            "\n\t\t\tu(x,0+)   = x*sin(3*x)/6"
            "\n\t\t\tu_t(x,0+) = sin(3*x)/6 + x*cos(3*x)/2"
            "\n\t\t\tu(0,t) = t*sin(3*t)"
            "\n\t\t\tu(L,t) = (L+t)*sin[3*(L+t)]/6\n"
            "\n\tThe analytical solution is\n\n"
            "\t\t         (x+t)*sin(3*(x+t))\n"
            "\t\tu(x,t) = ------------------\n"
            "\t\t                   6\n"
            "\n\tand its Laplace Transform is\n\n"
            "\t\t         sin(3*x)+3*x*cos(3*x)+s*x*sin(3*x)   3*sin(3*x)-s*cos(3*x)\n"
            "\t\tU(x,s) = ---------------------------------- - ---------------------\n"
            "\t\t                     6*(s^2+9)                      (s^2+9)^2\n"
            "\n\twith double poles at +/-3i\n"
            "\n\t     and abscissa of convergence: sigma0 = 0\n"
            "\n====================================================================================\n";
