# Establishing the links :

linkrc = ../../../Ada/Root_Counts/Stalift

links:
	@-ln -s $(linkrc)/bkkcomp.a     bkk_bound_computations.ads
	@-ln -s $(linkrc)/bkkcompB.a    bkk_bound_computations.adb
	@-ln -s $(linkrc)/contrimv.a    contributions_to_mixed_volume.ads
	@-ln -s $(linkrc)/contrimvB.a   contributions_to_mixed_volume.adb
	@-ln -s $(linkrc)/drivcrit.a    driver_for_criterion.ads
	@-ln -s $(linkrc)/drivcritB.a   driver_for_criterion.adb
	@-ln -s $(linkrc)/drivlift.a    drivers_for_lifting_functions.ads
	@-ln -s $(linkrc)/drivliftB.a   drivers_for_lifting_functions.adb
	@-ln -s $(linkrc)/drivstal.a    drivers_for_static_lifting.ads
	@-ln -s $(linkrc)/drivstalB.a   drivers_for_static_lifting.adb
	@-ln -s $(linkrc)/drivcomv.a    drivers_for_mixed_contributions.ads
	@-ln -s $(linkrc)/drivcomvB.a   drivers_for_mixed_contributions.adb
	@-ln -s $(linkrc)/cofltint.a    float_integer_convertors.ads
	@-ln -s $(linkrc)/cofltintB.a   float_integer_convertors.adb
	@-ln -s $(linkrc)/fltlift.a     float_lifting_functions.ads
	@-ln -s $(linkrc)/fltliftB.a    float_lifting_functions.adb
	@-ln -s $(linkrc)/fltlift_ut.a  float_lifting_utilities.ads
	@-ln -s $(linkrc)/fltlift_utB.a float_lifting_utilities.adb
	@-ln -s $(linkrc)/fltmisu.a     float_mixed_subdivisions.ads
	@-ln -s $(linkrc)/fltmisuB.a    float_mixed_subdivisions.adb
	@-ln -s $(linkrc)/fltmisu_io.a  float_mixed_subdivisions_io.ads
	@-ln -s $(linkrc)/fltmisu_ioB.a float_mixed_subdivisions_io.adb
	@-ln -s $(linkrc)/fltprune.a    float_pruning_methods.ads
	@-ln -s $(linkrc)/fltpruneB.a   float_pruning_methods.adb
	@-ln -s $(linkrc)/fltpolco.a    float_polyhedral_continuation.ads
	@-ln -s $(linkrc)/fltpolcoB.a   float_polyhedral_continuation.adb
	@-ln -s $(linkrc)/fltstali.a    float_static_lifting.ads
	@-ln -s $(linkrc)/fltstaliB.a   float_static_lifting.adb
	@-ln -s $(linkrc)/inncones.a    inner_normal_cones.ads
	@-ln -s $(linkrc)/innconesB.a   inner_normal_cones.adb
	@-ln -s $(linkrc)/intlift.a     integer_lifting_functions.ads
	@-ln -s $(linkrc)/intliftB.a    integer_lifting_functions.adb
	@-ln -s $(linkrc)/intlift_ut.a  integer_lifting_utilities.ads
	@-ln -s $(linkrc)/intlift_utB.a integer_lifting_utilities.adb
	@-ln -s $(linkrc)/comisudi.a    mixed_coherent_subdivisions.ads
	@-ln -s $(linkrc)/comisudiB.a   mixed_coherent_subdivisions.adb
	@-ln -s $(linkrc)/intmisu.a     integer_mixed_subdivisions.ads
	@-ln -s $(linkrc)/intmisuB.a    integer_mixed_subdivisions.adb
	@-ln -s $(linkrc)/intmisu_io.a  integer_mixed_subdivisions_io.ads
	@-ln -s $(linkrc)/intmisu_ioB.a integer_mixed_subdivisions_io.adb
	@-ln -s $(linkrc)/mivoco.a      mixed_volume_computation.ads
	@-ln -s $(linkrc)/mivocoB.a     mixed_volume_computation.adb
	@-ln -s $(linkrc)/noconint.a    normal_cone_intersections.ads
	@-ln -s $(linkrc)/noconintB.a   normal_cone_intersections.adb
	@-ln -s $(linkrc)/intprune.a    integer_pruning_methods.ads
	@-ln -s $(linkrc)/intpruneB.a   integer_pruning_methods.adb
	@-ln -s $(linkrc)/intpolco.a    integer_polyhedral_continuation.ads
	@-ln -s $(linkrc)/intpolcoB.a   integer_polyhedral_continuation.adb
	@-ln -s $(linkrc)/prunstat.a    pruning_statistics.ads
	@-ln -s $(linkrc)/prunstatB.a   pruning_statistics.adb
