#!/usr/bin/csh
#PBS -l nodes=8:whirlwind:ppn=1 -l walltime=15:00
exec pbslam -W /sciclone/home10/ancher/pcdm-1.0 $PBS_O_WORKDIR/pcdm $PBS_O_WORKDIR/models/chesapeake4000_madd.dat $PBS_O_WORKDIR/models/chesapeake4000_madd.cdt -a 706.25 -m 512 -s /sciclone/home10/ancher/pcdm-1.0/statistics/aggr_512/chesapeake4000_madd/8
