#!/usr/bin/csh
#PBS -l nodes=48:whirlwind:ppn=1 -l walltime=15:00
exec pbslam -W /sciclone/home10/ancher/pcdm-1.0 $PBS_O_WORKDIR/pcdm $PBS_O_WORKDIR/models/pipe4000_madd.dat $PBS_O_WORKDIR/models/pipe4000_madd.cdt -a 0.000607083333333 -m 64 -s /sciclone/home10/ancher/pcdm-1.0/statistics/aggr_64/pipe4000_madd/48
