char *str = "\n====================================================================================\n"
            "\n       >>>   Example 0a - OMP-based parallel Talbot Suite DE   <<<\n"
            "\n         Application of Talbot's method to solve the ODE equation\n"
            "\n\t\t\tf'''' + 18*f'' + 81*f = 0,         t>0\n"
            "\n\twith conditions:\n"
            "\n\t\t\tf(0) = f'(0) = f'''(0) = 0"
            "\n\t\t\tf''(0) = 1\n"
            "\n\tThe analytical solution is\n\n"
            "\t\tf(t) = t*sin(3*t)/6\n"
            "\n\tand its Laplace Transform is\n\n"
            "\t\t            s\n"
            "\t\tF(s) = -----------\n"
            "\t\t       (s^2 + 9)^2\n"
            "\n\twith double poles at +/-3i\n"
            "\n\t     and abscissa of convergence: sigma0 = 0\n"
            "\n====================================================================================\n";
