      DOUBLE PRECISION FUNCTION DLASMX( I )
      INTEGER I
*
      DOUBLE PRECISION OTHIRD
      PARAMETER ( OTHIRD = 1.0D+0/3.0D+0 )
      INTRINSIC DBLE
      DLASMX = DBLE( I )**OTHIRD
      RETURN
      END
