sudo: false
dist: xenial

language: python

python:
  - '3.6'

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - dvipng

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh
  - chmod +x $HOME/miniconda3.sh
  - "$HOME/miniconda3.sh -b;"
  - export PATH=/home/travis/miniconda3/bin:$PATH

install:
  - conda install --yes -c conda-forge mpich petsc4py mpi4py pyfftw fenics
  - conda install --yes pip numpy scipy matplotlib nose pep8 coverage sympy dill numba sphinx
  - conda list
  - pip install travis-sphinx
  - ln -sf /home/travis/miniconda3/lib/libstdc++.so.6.0.25 /home/travis/miniconda3/lib/libstdc++.so.6

script:
  - "./docs/update_apidocs.sh"
  - nosetests -v --with-coverage --cover-erase --cover-inclusive --cover-package=pySDC/core,pySDC/implementations,pySDC/helpers,pySDC/tutorial,pySDC/projects --cover-html --cover-html-dir=doc/build/test_coverage pySDC/tests
  - travis-sphinx build

after_success:
  - travis-sphinx deploy
