char *str = "\n====================================================================================\n"
            "\n               >>>   Example 1a - Talbot Suite DE   <<<\n"
            "\n         Application of Talbot's method to solve the PDE equation\n"
            "\n\t\t\tu_t (x,t) = u_x (x,t),         x > X0,  t>0\n"
            "\n\twith conditions:"
            "\n\t\t\tu(x,0+) = x"
            "\n\t\t\tu(X0,t) = X0 + t\n\n"
            "\n\tThe analytical solution is\n\n"
            "\t\tu(x,t) = x + t\n"
            "\n\tand its Laplace Transform is\n\n"
            "\t\t          1     x\n"
            "\t\tU(x,s) = --- + ---\n"
            "\t\t         s^2    s\n"
            "\n\twith a double pole at 0\n"
            "\n\t     and abscissa of convergence: sigma0 = 0\n"
            "\n====================================================================================\n";
