#!/bin/csh -f
#
# Create an ada.lib for VADS compiler with settings of ADAPATH.
#
# USAGE : remove # for target of interest.
# 
# for SUN/Solaris :
# set ADAPATH=/cw/sun5ada/Ada6.2.3-0/self
#
# for IBM/RS6000 AIX :
# set ADAPATH=/disks/zeno/lv02/vads/self
#
# for DEC/Ultrix :
set ADAPATH=/cw/vads.dec/v6.1.0d
#
a.mklib . $ADAPATH/verdixlib
