#line 2 "src/xml/XMLLexer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
static yyconst short int yy_accept[132] =
    {   0,
       34,   34,    0,    0,   13,   13,    9,    9,   17,   17,
       28,   28,    0,    0,    0,    0,    0,    0,    0,    0,
       37,   35,   34,   35,   12,    4,    3,    4,   14,   36,
       13,   11,   11,   36,    9,   10,   20,   17,   17,   20,
       20,   20,   18,   30,   29,   29,   28,   31,   32,   31,
       36,   36,   23,   36,   26,   26,    7,    6,   35,   35,
       34,   12,    0,    8,   27,    0,   13,    0,   10,    9,
       17,    0,    0,   18,    0,    0,   19,    0,    0,    0,
       29,   28,   33,    0,   23,    0,    0,    0,   23,    0,
       25,    0,    0,    0,    8,    0,    2,    0,   15,    0,

        0,   16,    0,   24,   24,    0,    1,    0,    0,    0,
       15,   15,   16,    0,    0,    0,   21,   15,    0,    0,
        0,   21,    0,    0,    0,   22,    0,    0,   22,    5,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,   12,
       13,   14,   15,    1,   10,   10,   16,   17,   18,   10,
       10,   10,   10,   10,   10,   19,   20,   10,   21,   22,
       10,   10,   10,   23,   10,   10,   10,   24,   25,   10,
        1,   26,    1,    1,   10,    1,   10,   10,   27,   28,

       29,   10,   10,   10,   30,   10,   10,   31,   32,   33,
       34,   35,   10,   36,   37,   38,   10,   39,   10,   40,
       41,   10,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    2,    2,    1,    1,    3,    4,    5,    1,    5,
        5,    6,    2,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5
    } ;

static yyconst short int yy_base[150] =
    {   0,
        0,    4,    1,    7,   16,   42,   68,   94,  120,  146,
      172,  198,    8,   12,   47,   99,   21,   23,   61,   62,
      381,  375,   30,  374,  212,  382,  382,  371,  382,  382,
        0,  382,   64,  113,    0,  382,  382,  128,  154,  115,
      363,   56,  382,  382,   37,   82,    0,  382,  382,  362,
      141,  369,   85,  332,  382,  341,  382,  382,  278,  277,
       87,  108,  162,  111,   39,  267,    0,  168,  382,    0,
      216,  266,  186,  382,  192,  220,  382,  229,    8,  273,
      137,    0,  382,  234,  162,  249,  270,  191,  206,  240,
      382,  268,  251,  237,  236,  208,  382,  140,  239,  157,

      264,  241,  256,  382,  249,  215,  382,  230,  199,  226,
      246,  248,  252,  190,  194,  168,  256,  258,  159,  128,
       95,  262,   86,   71,   56,  264,   23,    8,  266,  382,
      382,  284,  290,  296,  302,  308,  314,  320,  326,  332,
      338,  344,  346,  348,  352,  354,  357,  362,  368
    } ;

static yyconst short int yy_def[150] =
    {   0,
      132,  132,  133,  133,  134,  134,  135,  135,  136,  136,
      137,  137,  138,  138,  139,  139,  140,  140,  141,  141,
      131,  142,  142,  142,  131,  131,  131,  131,  131,  131,
      143,  131,  131,  131,  144,  131,  131,  131,  131,  145,
      131,  131,  131,  131,  131,  131,  146,  131,  131,  131,
      131,  147,  131,  131,  131,  131,  131,  131,  142,  142,
      142,  131,  131,  131,  131,  131,  143,  131,  131,  144,
      131,  131,  131,  131,  131,  145,  131,  131,  148,  149,
      131,  146,  131,  131,  131,  131,  131,  147,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  148,  131,  148,

      149,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  148,  131,  131,  131,  131,  131,  148,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
        0,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131
    } ;

static yyconst short int yy_nxt[424] =
    {   0,
      131,   23,   23,   27,   24,   23,   23,   28,   24,   27,
       49,   25,   99,   28,   49,   25,   29,   29,   30,   29,
       29,   29,   50,   30,   29,   30,   50,   29,   29,   29,
       29,   61,   61,  100,   60,   56,  130,   56,   81,   81,
      130,   29,   29,   29,   30,   29,   29,   29,   51,   51,
       29,   52,   52,   29,   29,   29,   29,   78,   78,   53,
       79,   80,   96,   30,   30,   68,   68,   29,   32,   33,
       34,   32,   32,   32,   58,   58,   32,   69,   96,   32,
       32,   36,   32,   81,   81,   54,   89,   89,   61,   61,
      128,   60,  127,   32,   32,   33,   34,   32,   32,   32,

       51,   51,   32,   52,   52,   32,   32,   36,   32,   62,
       62,   53,   95,   95,   68,   68,   75,   75,  126,   32,
       37,   38,   39,   37,   37,   37,   69,   73,   41,   71,
       71,   37,   42,   43,   37,  125,   72,   54,   81,   81,
       73,   74,   84,   84,   99,   37,   37,   38,   39,   37,
       37,   37,  124,   85,   41,   71,   71,   37,   42,   43,
       37,  112,   72,   89,   89,  100,   73,   74,   92,   68,
       68,   37,   44,   45,   46,   44,   44,   44,   93,   86,
       44,   69,  100,   44,   44,   44,   44,   78,   78,   94,
       79,   80,  123,   75,   75,  104,  105,   44,   44,   45,

       46,   44,   44,   44,   73,  121,   44,   89,   89,   44,
       44,   44,   44,   62,   62,   63,  120,   71,   71,  119,
       64,   75,   75,   44,   72,  116,   65,  110,   73,   74,
       78,   78,   73,   79,   80,   84,   84,   95,   95,  110,
      111,  111,  113,  113,  117,  115,   85,  111,  111,  118,
      118,  114,   99,  113,  113,  103,  117,  122,  122,  118,
      118,   88,   99,  122,  122,  129,  129,  129,  129,  102,
      109,  108,   86,  100,  107,  106,  103,   90,  102,   77,
       97,   60,   60,  100,   22,   22,   22,   22,   22,   22,
       26,   26,   26,   26,   26,   26,   31,   31,   31,   31,

       31,   31,   35,   35,   35,   35,   35,   35,   40,   40,
       40,   40,   40,   40,   47,   47,   47,   47,   47,   47,
       48,   48,   48,   48,   48,   48,   30,   30,   30,   30,
       30,   30,   55,   55,   55,   55,   55,   55,   57,   57,
       57,   57,   57,   57,   59,   59,   59,   59,   59,   67,
       67,   70,   70,   76,   91,   76,   76,   82,   82,   88,
       90,   88,   98,   98,   98,   98,   98,   98,  101,  101,
      101,  101,  101,  101,   87,   83,   77,   66,   60,   60,
      131,   21,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,

      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131
    } ;

static yyconst short int yy_chk[424] =
    {   0,
        0,    1,    1,    3,    1,    2,    2,    3,    2,    4,
       13,    1,   79,    4,   14,    2,    5,    5,    5,    5,
        5,    5,   13,   17,    5,   18,   14,    5,    5,    5,
        5,   23,   23,   79,   23,   17,  128,   18,   45,   45,
      127,    5,    6,    6,    6,    6,    6,    6,   15,   15,
        6,   15,   15,    6,    6,    6,    6,   42,   42,   15,
       42,   42,   65,   19,   20,   33,   33,    6,    7,    7,
        7,    7,    7,    7,   19,   20,    7,   33,   65,    7,
        7,    7,    7,   46,   46,   15,   53,   53,   61,   61,
      125,   61,  124,    7,    8,    8,    8,    8,    8,    8,

       16,   16,    8,   16,   16,    8,    8,    8,    8,   62,
       62,   16,   64,   64,   34,   34,   40,   40,  123,    8,
        9,    9,    9,    9,    9,    9,   34,   40,    9,   38,
       38,    9,    9,    9,    9,  121,   38,   16,   81,   81,
       38,   38,   51,   51,   98,    9,   10,   10,   10,   10,
       10,   10,  120,   51,   10,   39,   39,   10,   10,   10,
       10,  100,   39,   85,   85,   98,   39,   39,   63,   68,
       68,   10,   11,   11,   11,   11,   11,   11,   63,   51,
       11,   68,  100,   11,   11,   11,   11,   73,   73,   63,
       73,   73,  119,   75,   75,   88,   88,   11,   12,   12,

       12,   12,   12,   12,   75,  116,   12,   89,   89,   12,
       12,   12,   12,   25,   25,   25,  115,   71,   71,  114,
       25,   76,   76,   12,   71,  109,   25,   96,   71,   71,
       78,   78,   76,   78,   78,   84,   84,   95,   95,   96,
       99,   99,  102,  102,  110,  108,   84,  111,  111,  112,
      112,  106,  112,  113,  113,  105,  110,  117,  117,  118,
      118,  103,  118,  122,  122,  126,  126,  129,  129,  101,
       94,   93,   84,  112,   92,   90,   87,   86,   80,   72,
       66,   60,   59,  118,  132,  132,  132,  132,  132,  132,
      133,  133,  133,  133,  133,  133,  134,  134,  134,  134,

      134,  134,  135,  135,  135,  135,  135,  135,  136,  136,
      136,  136,  136,  136,  137,  137,  137,  137,  137,  137,
      138,  138,  138,  138,  138,  138,  139,  139,  139,  139,
      139,  139,  140,  140,  140,  140,  140,  140,  141,  141,
      141,  141,  141,  141,  142,  142,  142,  142,  142,  143,
      143,  144,  144,  145,   56,  145,  145,  146,  146,  147,
       54,  147,  148,  148,  148,  148,  148,  148,  149,  149,
      149,  149,  149,  149,   52,   50,   41,   28,   24,   22,
       21,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,

      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "src/xml/xml.lex"
#define INITIAL 0
/*==================================================================*/
/* description  : xml lexer                                         */
/* author       : Walter Schreppers                                 */
/* created      : 9/1/2002                                          */
/* modified     : /                                                 */
/* bugs         : /                                                 */
/*==================================================================*/  
/* generate c++ class */
#line 18 "src/xml/xml.lex"
  /*==================================================================*/
  /* includes                                                         */
  /*==================================================================*/
  #include "XMLParser.h"
  #include <errno.h>



  
  /*==================================================================*/
  /* variables and functions for lexer                                */
  /*==================================================================*/
  int LineNr=1; //keep track of line 
  int column=1; //keep track of the column
  
  void resetXMLLineCol(){
    LineNr=1;
    column=1;
  }

  XMLParser* parser;
  void setXMLParser(XMLParser* p){
    parser=p;
  }

  int getXMLLineNr(){
    return LineNr;
  } 
  
   
  int getXMLColumn(){
    return column;
  }



  //---------------------------------------------
  // keep track of line and column 
  //
  void count(char* lextext){
    int i;
    for (i = 0; lextext[i] != '\0'; i++){
      if (lextext[i] == '\n'){
        column = 1;
        LineNr++;
      }
      else if (lextext[i] == '\t'){
        column += 8 - (column % 8);
      }
      else{
        column++;
      }
    }
  }

 
/*==================================================================*/
/* STATES AND SOME LEXER DEFS                                       */
/*==================================================================*/
#define S_COMMENT 1
 
#define S_TAG_OPEN 2
 
#define S_TAG_CLOSE 3
 
#define S_TAG 4

#define S_PROCESS_TAG 5

#define S_PROCESS_TAG_DATA 6

#define S_PROLOG 7

#define S_PROLOG_END 8

#define S_DOCTYPE 9

#line 552 "src/xml/XMLLexer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 105 "src/xml/xml.lex"


  /*==================================================================*/
  /* TOKEN RECOGNITION                                                */
  /*==================================================================*/

  /*------------------------- comments -------------------------------*/

  /*last minute change, since comments are apperantly */ 
  /*allowed outside document root, we don't return anything */
  /*to the parser here!!! Which means comment nodes are just ommitted and not put in the tree*/

#line 692 "src/xml/XMLLexer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &std::cin;

		if ( ! yyout )
			yyout = &std::cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 132 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 382 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "src/xml/xml.lex"
{
                count(yytext);
                BEGIN(S_COMMENT);
                //return XMLParser::COMMENT_BEGIN;
              }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 123 "src/xml/xml.lex"
{                                            
                        count(yytext);
                        BEGIN(INITIAL);                                 
                        //return XMLParser::COMMENT_END;
                      }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 128 "src/xml/xml.lex"
{
                        LineNr++;
                        //parser->yylval.str=new string("\n");
                        //return XMLParser::COMMENT_DATA;
                      }                                                                 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 133 "src/xml/xml.lex"
{                                              
                        count(yytext);
                        //parser->yylval.str=new string(yytext);
                        //return XMLParser::COMMENT_DATA;
                      }                                           
	YY_BREAK
/*-----------------------simplified doctype spec--------------------*/
case 5:
YY_RULE_SETUP
#line 141 "src/xml/xml.lex"
{
                                  count(yytext);
                                  BEGIN(S_DOCTYPE);
                             }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 145 "src/xml/xml.lex"
{
                                  count(yytext);
                                  BEGIN(INITIAL);
                                  return XMLParser::DOCTYPE;
                                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 150 "src/xml/xml.lex"
{
                                  count(yytext);
                                }
	YY_BREAK
/*------------------------- tags -----------------------------------*/
case 8:
YY_RULE_SETUP
#line 157 "src/xml/xml.lex"
{
                        count(yytext);
                        BEGIN(S_TAG_CLOSE);
                      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 162 "src/xml/xml.lex"
{
                            count(yytext);
                            parser->yylval.str=new string(yytext);
                            return XMLParser::CLOSE_TAG;
                          }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 169 "src/xml/xml.lex"
{
                            count(yytext);
                            BEGIN(INITIAL);
                            return XMLParser::CLOSE_TAG_END;
                          }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 174 "src/xml/xml.lex"
{
                            count(yytext);
                            string errorStr="invalid char in closing tag '"+string(yytext)+"'";
                            parser->syntaxError(errorStr);
                            return EOF;
                          }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 181 "src/xml/xml.lex"
{
                BEGIN(S_TAG_OPEN);
              }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 186 "src/xml/xml.lex"
{
                    count(yytext);
                    parser->yylval.str=new string(yytext);
                    BEGIN(S_TAG);
                    return XMLParser::OPEN_TAG_BEGIN;
                  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 194 "src/xml/xml.lex"
{
                count(yytext);
                string errorStr="invalid char in open tag '"+string(yytext)+"'";
                parser->syntaxError(errorStr);
                return EOF;
              }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 201 "src/xml/xml.lex"
{
                                                  count(yytext);
                                                  parser->yylval.str=new string(yytext);
                                                  return XMLParser::ATTRIBUTE; 
                                                }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "src/xml/xml.lex"
{
                                                  count(yytext);
                                                  parser->yylval.str=new string(yytext);
                                                  return XMLParser::ATTRIBUTE; 
                                                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 211 "src/xml/xml.lex"
{ count(yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 212 "src/xml/xml.lex"
{
                          count(yytext);
                          BEGIN(INITIAL);
                          return XMLParser::OPEN_TAG_END;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 217 "src/xml/xml.lex"
{
                          count(yytext);
                          BEGIN(INITIAL);
                          return XMLParser::SINGLE_TAG_END;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 223 "src/xml/xml.lex"
{
                count(yytext);
                string errorStr="invalid tag argument '"+string(yytext)+"'";
                parser->syntaxError(errorStr);
                return EOF;
              }
	YY_BREAK
/*------------- simple document prolog/xml version -----------------*/
case 21:
YY_RULE_SETUP
#line 236 "src/xml/xml.lex"
{
                                  count(yytext);
                                  BEGIN(S_PROLOG);
                                  return XMLParser::PROLOG_START;
                                }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 242 "src/xml/xml.lex"
{
                                  count(yytext);
                                  return XMLParser::VERSION;
                                }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 246 "src/xml/xml.lex"
{
                                  count(yytext);
                                  return XMLParser::EQ;
                                }                                
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 250 "src/xml/xml.lex"
{
                                  count(yytext);
                                  parser->yylval.str=new string(yytext);
                                  BEGIN(S_PROLOG_END);
                                  return XMLParser::NR;
                                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 256 "src/xml/xml.lex"
{
                                  count(yytext);
                                  BEGIN(INITIAL);
                                  return XMLParser::PROLOG_END;
                                }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 261 "src/xml/xml.lex"
{
                                   count(yytext);
                                   parser->yylval.str=new string(yytext);
                                   return XMLParser::PROCESS_TAG_DATA;
                                }
	YY_BREAK
/*------------------------processing instructions-------------------*/
case 27:
YY_RULE_SETUP
#line 270 "src/xml/xml.lex"
{
                        count(yytext);
                        BEGIN(S_PROCESS_TAG);
                      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 274 "src/xml/xml.lex"
{
                        //target string...
                        count(yytext);
                        parser->yylval.str=new string(yytext);
                        //BEGIN(S_PROCESS_TAG_DATA);
                        return XMLParser::PROCESS_TAG_TARGET;                        
                      }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 281 "src/xml/xml.lex"
{
                        BEGIN(S_PROCESS_TAG_DATA);
                      }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 284 "src/xml/xml.lex"
{
                        count(yytext);
                        string errorStr="invalid tag argument '"+string(yytext)+"'";
                        parser->syntaxError(errorStr);
                        return EOF;
                      }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 292 "src/xml/xml.lex"
{
                                            count(yytext);
                                            parser->yylval.str=new string(yytext);
                                            return XMLParser::PROCESS_TAG_DATA;
                                          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 297 "src/xml/xml.lex"
{
                                            LineNr++;
                                            parser->yylval.str=new string("\n");
                                            return XMLParser::PROCESS_TAG_DATA;
                                          }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 303 "src/xml/xml.lex"
{
                                            count(yytext);
                                            BEGIN(INITIAL);
                                            return XMLParser::PROCESS_TAG_END;
                                          }
	YY_BREAK
/*--------------- formatting, errors and textnodes ----------------*/
case 34:
YY_RULE_SETUP
#line 315 "src/xml/xml.lex"
{
                  count(yytext);
                  parser->yylval.str=new string(yytext);
                  return XMLParser::WHITESPACE;
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 321 "src/xml/xml.lex"
{
                  count(yytext);
                  parser->yylval.str=new string(yytext);
                  return XMLParser::TEXTNODE;
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 327 "src/xml/xml.lex"
ECHO;
	YY_BREAK
#line 1093 "src/xml/XMLLexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_COMMENT):
case YY_STATE_EOF(S_TAG_OPEN):
case YY_STATE_EOF(S_TAG_CLOSE):
case YY_STATE_EOF(S_TAG):
case YY_STATE_EOF(S_PROCESS_TAG):
case YY_STATE_EOF(S_PROCESS_TAG_DATA):
case YY_STATE_EOF(S_PROLOG):
case YY_STATE_EOF(S_PROLOG_END):
case YY_STATE_EOF(S_DOCTYPE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 132 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 132 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 131);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( std::istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	std::cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 327 "src/xml/xml.lex"


