char *str = "\n====================================================================================\n"
            "\n               >>>   Example 5 - Talbot Suite DE   <<<\n"
            "\n         Application of Talbot's method to solve the PDE equation\n"
            "\n\t\t\tu_t (x,y,t) = u_xx (x,y,t) + u_yy (x,y,t),      0 < x,y < 1,  t>0\n"
            "\n\twith conditions:"
            "\n\t\t\tu(x,y,0+) = x*(x-1) + y*(y-1)"
            "\n\t\t\tu(0,y,t) = u(1,y,t) = 4*t + y*(y-1)"
            "\n\t\t\tu(x,0,t) = u(x,1,t) = 4*t + x*(x-1)\n"
            "\n\tThe analytical solution is\n\n"
            "\t\tu(x,y,t) = 4*t + x*(x-1) + y*(y-1)\n"
            "\n\tand its Laplace Transform is\n\n"
            "\t\t            4    x*(x-1) + y*(y-1)\n"
            "\t\tU(x,y,s) = --- + -----------------\n"
            "\t\t           s^2           s\n"
            "\n\twith a double pole at 0\n"
            "\n\t     and abscissa of convergence: sigma0 = 0\n"
            "\n====================================================================================\n";
