COMOBJ=Abramowitz.o Flocke.o NumRecipeHQRL.o StrobachLDLT.o common.o FastQuarticSolver.o NumRecipeHQR.o  Shmakov.o 

drivers: $(COMOBJ) 

Abramowitz.o: Abramowitz.c
	$(CC) $(CFLAGS) $(OF) -c Abramowitz.c 

Flocke.o: Flocke.c
	$(CC) $(CFLAGS) $(OF) -c Flocke.c 

NumRecipeHQR.o: NumRecipeHQR.c
	$(CC) $(CFLAGS) $(OF) -c NumRecipeHQR.c 

NumRecipeHQRL.o: NumRecipeHQRL.c
	$(CC) $(CFLAGS) $(OF) -c NumRecipeHQRL.c 

StrobachLDLT.o: StrobachLDLT.c
	$(CC) $(CFLAGS) $(OF) -c StrobachLDLT.c 

FastQuarticSolver.o: FastQuarticSolver.c
	$(CC) $(CFLAGS) $(OF) -c FastQuarticSolver.c

Shmakov.o: Shmakov.c
	$(CC) $(CFLAGS) $(OF) -c Shmakov.c

common.o: common.c
	$(CC) $(CFLAGS) $(OF) -c common.c
