# LaTeX2HTML 96.1-h (September 30, 1996)
# Associate images original text with physical files.

$key = q/{figure}[htbp]vspace*4.0inhspace*0.75inspecialpsfile=spawn.epshscale=70vscale=70vspace0invspace*-3mmlabelspawn{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=524 HEIGHT=363 ALIGN=BOTTOM ALT="figure983" SRC="img29.gif">|; 
$key = q/{_inline}$lambda(b)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=28 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1655" SRC="img79.gif">|; 
$key = q/{_inline}$cne0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=39 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1567" SRC="img55.gif">|; 
$key = q/{_inline}$2^51${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1419" SRC="img24.gif">|; 
$key = q/{_inline}$2^pL${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=35 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1413" SRC="img21.gif">|; 
$key = q/{_inline}$S_0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=16 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline1403" SRC="img18.gif">|; 
$key = q/{_inline}$[0,1)^s${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=41 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1635" SRC="img76.gif">|; 
$key = q/{_inline}${u_i}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=31 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1337" SRC="img4.gif">|; 
$key = q/{_inline}$u_i,u_i+4N,...${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=89 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1387" SRC="img14.gif">|; 
$key = q/{_inline}$2^m-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline1495" SRC="img38.gif">|; 
$key = q/{_inline}$x_n=sum_i=0^log_bna_ib^-i-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=150 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline1685" SRC="img85.gif">|; 
$key = q/{_inline}$2^26${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1417" SRC="img23.gif">|; 
$key = q/{_inline}$S_k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline1395" SRC="img15.gif">|; 
$key = q/{_inline}$u_i,u_i+M,...${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=85 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1425" SRC="img25.gif">|; 
$key = q/{_inline}$D_s(x_i)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=49 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1627" SRC="img75.gif">|; 
$key = q/{_inline}$10^12${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=29 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1333" SRC="img3.gif">|; 
$key = q/{_inline}$(2^k-1)2^m-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline1555" SRC="img47.gif">|; 
$key = q/{_inline}${x_npmod2^j}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=120 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline1477" SRC="img31.gif">|; 
$key = q/{_inline}$u_iLM,u_iLM+1,...${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=136 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1431" SRC="img26.gif">|; 
$key = q/{_inline}$a_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1523" SRC="img43.gif">|; 
$key = q/{figure}[htbp]vspace*5inhspace*0.5inspecialpsfile=E.metro.lcg.par.pshscale=60vscale=60vspace-1.5invspace*3mmlabelE.metro.lcg.par{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=474 HEIGHT=375 ALIGN=BOTTOM ALT="figure1102" SRC="img68.gif">|; 
$key = q/{_inline}$O(log_2m)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=73 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1571" SRC="img57.gif">|; 
$key = q/{_inline}$inej${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1485" SRC="img35.gif">|; 
$key = q/{_inline}$langle|C(j,l,k)|^2rangle=k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=127 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline1601" SRC="img65.gif">|; 
$key = q/{_inline}$langle|C_g(k)|^2rangle=k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=105 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline1593" SRC="img62.gif">|; 
$key = q/{_inline}$I_k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline1347" SRC="img7.gif">|; 
$key = q/{_inline}$(2^k-1)2^m-3${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=96 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline1559" SRC="img50.gif">|; 
$key = q/{_inline}$O(N^-12)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline1667" SRC="img83.gif">|; 
$key = q/{_inline}$barc${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline1561" SRC="img53.gif">|; 
$key = q/{_inline}$10^5${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1329" SRC="img1.gif">|; 
$key = q/{_inline}$bar0=0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1569" SRC="img56.gif">|; 
$key = q/{_inline}$s^th${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=19 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1637" SRC="img77.gif">|; 
$key = q/{_inline}$#(B,x_i)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=62 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1657" SRC="img80.gif">|; 
$key = q/{_inline}$u=I2^-n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=69 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline1351" SRC="img8.gif">|; 
$key = q/{_inline}$n=sum_i=0^log_bna_ib^i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=114 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline1683" SRC="img84.gif">|; 
$key = q/{_inline}$x_n${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1521" SRC="img42.gif">|; 
$key = q/{figure}vspace*3inhspace*0.25inspecialpsfile=states.epshscale=70vscale=70vspace*-3mmlabelstates{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=656 HEIGHT=383 ALIGN=BOTTOM ALT="figure953" SRC="img19.gif">|; 
$key = q/{_inline}$u_k=F(S_k)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=86 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1399" SRC="img16.gif">|; 
$key = q/{_inline}$calP${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline1453" SRC="img28.gif">|; 
$key = q/{_inline}$10^10${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=29 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1613" SRC="img69.gif">|; 
$key = q/{_inline}$2^p${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline1405" SRC="img20.gif">|; 
$key = q/{_inline}$sqrtm2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=48 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline1491" SRC="img37.gif">|; 
$key = q/{_inline}$x_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1623" SRC="img73.gif">|; 
$key = q/{_inline}$gne0${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=40 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1595" SRC="img63.gif">|; 
$key = q/{_inline}$N^-12${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=46 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1619" SRC="img70.gif">|; 
$key = q/{_inline}$gcd(b_i,b_j)=1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=105 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1483" SRC="img34.gif">|; 
$key = q/{_inline}$cbarcequiv1pmodm${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=131 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1565" SRC="img54.gif">|; 
$key = q/{_inline}$2^j${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=13 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline1479" SRC="img32.gif">|; 
$key = q/{_inline}$u_0,...,u_k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=64 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1591" SRC="img60.gif">|; 
$key = q/{_inline}$ell_j${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1505" SRC="img40.gif">|; 
$key = q/{figure}vspace*4.5inhspace*0.35inspecialpsfile=rw3.pshscale=60vscale=60vspace*-1.9invspace*-3mmlabelrandomwalk{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=449 HEIGHT=352 ALIGN=BOTTOM ALT="figure935" SRC="img11.gif">|; 
$key = q/{_inline}${b_j}${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=30 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1481" SRC="img33.gif">|; 
$key = q/{_inline}$u_i+4N${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1385" SRC="img13.gif">|; 
$key = q/{_inline}$a_j=a^ell_jpmodm${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=145 HEIGHT=32 ALIGN=MIDDLE ALT="tex2html_wrap_inline1503" SRC="img39.gif">|; 
$key = q/{_inline}$10^7${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1331" SRC="img2.gif">|; 
$key = q/{_inline}$T_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline1451" SRC="img27.gif">|; 
$key = q/{_inline}$[1,2^n)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=43 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1341" SRC="img5.gif">|; 
$key = q/{_inline}$u_k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=17 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline1345" SRC="img6.gif">|; 
$key = q/{_inline}$U_i^n=(u_i+1,...u_i+n)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=146 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1361" SRC="img9.gif">|; 
$key = q/{_inline}$u_i${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=14 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1383" SRC="img12.gif">|; 
$key = q/{_inline}$b_j${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=11 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline1487" SRC="img36.gif">|; 
$key = q/{_inline}$2^(k-1)times(m-1)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=92 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1557" SRC="img48.gif">|; 
$key = q/{_inline}$10^11${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=29 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1603" SRC="img66.gif">|; 
$key = q/{_inline}$S_k+1=T(S_k)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=102 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1401" SRC="img17.gif">|; 
$key = q/{_inline}$x_n+k${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=36 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline1539" SRC="img45.gif">|; 
$key = q/{_inline}$2^k-1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=44 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline1525" SRC="img44.gif">|; 
$key = q/{_inline}$16times16${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=54 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline1607" SRC="img67.gif">|; 
$key = q/{figure}centervspace*-4mmfboxhspace*0.25inminipage[t]4.0innoindentflushlefthspace0.2in_inline$x=0$_inlinehspace0.2inrepeatloopNtimeshspace0.4in_inline$xtrial=x+delta*(sprng()-0.5)$_inlinehspace0.4inif_inline$(exp(-beta*(V(xtrial)-V(x)));SPMgt;sprng())$_inlinethenhspace0.6in_inline$x=xtrial$_inlinehspace0.4inifhspace0.2inloopflushleftvspace*2mmminipagehspace*0.25incentervspace*-4mmlabelmoveparticle{figure}/;
$cached_env_img{$key} = q|<IMG WIDTH=541 HEIGHT=164 ALIGN=BOTTOM ALT="figure912" SRC="img10.gif">|; 
$key = q/{_inline}$10^8${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=22 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap_inline1415" SRC="img22.gif">|; 
$key = q/{_inline}$exp(-V(R)k_BT)${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=138 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline1689" SRC="img87.gif">|; 
$key = q/{_inline}$odot${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline1573" SRC="img59.gif">|; 

1;

