# Establishing the links :

linkrc = ../../../Ada/Root_Counts/Implift

links:
	@-ln -s $(linkrc)/transfo.a     transformations.ads
	@-ln -s $(linkrc)/transfoB.a    transformations.adb
	@-ln -s $(linkrc)/transfo_io.a  transformations_io.ads
	@-ln -s $(linkrc)/transfo_ioB.a transformations_io.adb
	@-ln -s $(linkrc)/tranlists.a   transforming_integer_vector_lists.ads
	@-ln -s $(linkrc)/tranlistsB.a  transforming_integer_vector_lists.adb
	@-ln -s $(linkrc)/tranlaur.a    transforming_laurent_systems.ads
	@-ln -s $(linkrc)/tranlaurB.a   transforming_laurent_systems.adb
	@-ln -s $(linkrc)/transols.a    transforming_solutions.ads
	@-ln -s $(linkrc)/transolsB.a   transforming_solutions.adb
	@-ln -s $(linkrc)/intvec_ut.a   integer_vectors_utilities.ads
	@-ln -s $(linkrc)/intvec_utB.a  integer_vectors_utilities.adb
	@-ln -s $(linkrc)/lstivc_ut.a   lists_of_vectors_utilities.ads
	@-ln -s $(linkrc)/lstivc_utB.a  lists_of_vectors_utilities.adb
	@-ln -s $(linkrc)/arrlivc_ut.a  arrays_of_lists_utilities.ads
	@-ln -s $(linkrc)/arrlivc_utB.a arrays_of_lists_utilities.adb
	@-ln -s $(linkrc)/tv.a          trees_of_vectors.ads
	@-ln -s $(linkrc)/tvB.a         trees_of_vectors.adb
	@-ln -s $(linkrc)/tv_io.a       trees_of_vectors_io.ads
	@-ln -s $(linkrc)/tv_ioB.a      trees_of_vectors_io.adb
	@-ln -s $(linkrc)/facenusu.a    face_enumerator_of_sum.ads
	@-ln -s $(linkrc)/facenusuB.a   face_enumerator_of_sum.adb
	@-ln -s $(linkrc)/volumes.a     volumes.ads
	@-ln -s $(linkrc)/volumesB.a    volumes.adb
	@-ln -s $(linkrc)/powlis.a      power_lists.ads
	@-ln -s $(linkrc)/powlisB.a     power_lists.adb
	@-ln -s $(linkrc)/binom.a       binomials.ads
	@-ln -s $(linkrc)/binomB.a      binomials.adb
	@-ln -s $(linkrc)/fewnom.a      fewnomials.ads
	@-ln -s $(linkrc)/fewnomB.a     fewnomials.adb
	@-ln -s $(linkrc)/durker.a      durand_kerner.ads
	@-ln -s $(linkrc)/durkerB.a     durand_kerner.adb
	@-ln -s $(linkrc)/mihoco.a      mixed_homotopy_continuation.ads
	@-ln -s $(linkrc)/mihocoB.a     mixed_homotopy_continuation.adb
	@-ln -s $(linkrc)/setsvol.a     set_structures_and_volumes.ads
	@-ln -s $(linkrc)/setsvolB.a    set_structures_and_volumes.adb
	@-ln -s $(linkrc)/vertices.a    vertices.ads
	@-ln -s $(linkrc)/verticesB.a   vertices.adb
	@-ln -s $(linkrc)/genpos.a      generic_position.ads
	@-ln -s $(linkrc)/genposB.a     generic_position.adb
	@-ln -s $(linkrc)/drivpts.a     drivers_for_vertex_points.ads
	@-ln -s $(linkrc)/drivptsB.a    drivers_for_vertex_points.adb
	@-ln -s $(linkrc)/drivplc.a     driver_for_polyhedral_continuation.ads
	@-ln -s $(linkrc)/drivplcB.a    driver_for_polyhedral_continuation.adb
	@-ln -s $(linkrc)/drivimpl.a    drivers_for_implicit_lifting.ads
	@-ln -s $(linkrc)/drivimplB.a   drivers_for_implicit_lifting.adb
