      SUBROUTINE ZZBFOR ( TESTCH, STATUS, SUBR, WRTSUM, SEELVL, WRITFL,
     -                                                     IW, RW, DW )

C## A R G U M E N T S:
                      LOGICAL           WRTSUM, WRITFL
                      INTEGER           SUBR,   SEELVL,  STATUS, IW(*)
                      CHARACTER * 1     TESTCH
                      REAL             RW(*)
                      DOUBLE PRECISION DW(*)

C## S T A T U S:
C               SINGLE/DOUBLE CONVERSION:        NOT REQUIRED.
C               SYSTEM  DEPENDENCE:                      NONE.
C
C>RCS $HEADER: BFOR.F,V 1.10 91/11/20 10:52:37 BUCKLEY EXP $
C>RCS $LOG:     BFOR.F,V $
C>RCS REVISION 1.10  91/11/20  10:52:37  BUCKLEY
C>RCS FINAL SUBMISSION TO TOMS
C>RCS
C>RCS REVISION 1.9  89/06/30  13:38:12  BUCKLEY
C>RCS PREPARING SUBMITTED VERSION OF MT
C>RCS
C>RCS REVISION 1.3.1.1  89/05/20  16:42:30  BUCKLEY
C>RCS TEMP. TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.3  89/05/18  12:20:16  BUCKLEY
C>RCS FINAL TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.2  89/05/15  14:47:03  BUCKLEY
C>RCS INITIAL INSTALLATION OF MT INTO RCS FORM.
C>RCS
C>RCS REVISION 1.1  89/01/17  16:50:06  BUCKLEY
C>RCS INITIAL REVISION
C>RCS
C
C## D E S C R I P T I O N:
C
C     THIS ROUTINE IS CALLED JUST BEFORE RUNNING EACH TEST PROBLEM.
C     THIS ALLOWS FOR OUTPUT OF ANY SPECIAL USER INFORMATION.
C
C     PARAMETER DESCRIPTION:
C
C         TESTCH - USED IN THE TEMPUN FILE TO FLAG DATA TO BE PROCESSED
C                  IN ZZSMRY.
C         STATUS - SAME AS IN ZZINK, SEE THAT SUBROUTINE FOR
C                  DESCRIPTION.
C         SUBR   - THE NUMBER OF THE SUBROUTINE BEING USED.
C         WRTSUM - COPY SUMMARY TO WRITE UNIT IF TRUE.
C         SEELEV - CONTROLS THE AMOUNT OF SUMMARY DATA SHOWN ON THE
C                  SCREEN (TAKES ON AN INTEGER VALUE FROM 1 TO 4).
C         WRITFL - COPY OUTPUT OF THE TEST TO THE WRITE UNIT IF TRUE.
C
C## E N T R Y   P O I N T S: THE NATURAL ENTRY ZZBFOR
C## S U B R O U T I N E S:   NONE ARE CALLED.
C## P A R A M E T E R S:
C-----                   DEFINITIONS OF THE I/O UNITS.

      INTEGER     PREPRC,     DAUF,       INPTUN
      PARAMETER ( PREPRC = 1, DAUF =   2, INPTUN = 3 )

      INTEGER     TEMPUN,     STDIN,     TRMOUT
      PARAMETER ( TEMPUN = 4, STDIN = 5, TRMOUT = 6 )

      INTEGER     WRITUN,     TRACUN,     SUMMUN
      PARAMETER ( WRITUN = 7, TRACUN = 8, SUMMUN = 9 )

      INTEGER     COPYUN,     TEXUN
      PARAMETER ( COPYUN =10, TEXUN =11 )
C-----                   DEFINITION OF SEELEVEL CONSTANTS

      INTEGER     CNONE,     CMIN,     CMED,     CFULL
      PARAMETER ( CNONE = 1, CMIN = 2, CMED = 3, CFULL = 4 )
C-----                   DEFINITION OF STATUS CODES.

C--ON ENTRY:
      INTEGER     CNORML,     CRCSTR,     CRCRPT,     CRCNFG
      PARAMETER ( CNORML = 0, CRCSTR = 1, CRCRPT = 2, CRCNFG = 3 )

      INTEGER     CNRMFG,      CPSTHR
      PARAMETER ( CNRMFG = -1, CPSTHR = -2 )

C--ON EXIT:
      INTEGER     CDONE,     CRCF,     CRCFG,     CRCG
      PARAMETER ( CDONE = 0, CRCF = 1, CRCFG = 2, CRCG = 3 )

      INTEGER     CNSTOR,      CIPMIN,      CIPUNF,      CBDMTH
      PARAMETER ( CNSTOR = -1, CIPMIN = -2, CIPUNF = -3, CBDMTH = -4 )

      INTEGER     CLSFAL,      CNODSC,      CXSFNC,      CPSBCK
      PARAMETER ( CLSFAL = -5, CNODSC = -6, CXSFNC = -7, CPSBCK = -8  )

      INTEGER     CRABRT,      CUSERV
      PARAMETER ( CRABRT = -9, CUSERV = -10 )

C## L O C A L   D E C L:     NONE ARE DEFINED.
C## S A V E:                 NONE SELECTED.
C## E Q U I V A L E N C E S: NONE ARE DEFINED.
C## C O M M O N:             NONE IS DEFINED.
C## D A T A:                 NONE ARE SET.
C##                                                E X E C U T I O N
C##                                                E X E C U T I O N

      GOTO ( 1000, 2000 ) SUBR

C-----NOTHING TO DO FOR BBLNIR.

 1000 GOTO 90000

C-----NOTHING TO DO FOR SHANNO'S CONMIN.

 2000 GOTO 90000

C## E X I T
90000       RETURN

C## F O R M A T S:  NONE ARE DEFINED.
C##                 E N D         OF ZZBFOR.
                    END
