      SUBROUTINE ZZLPCK ( LOOPC, LOOPX, ORDER, PT, VALUE )

C## A R G U M E N T S:
                      INTEGER  LOOPX(*), ORDER(*), PT
                      REAL              LOOPC(*), VALUE
C!!!!                 DOUBLE PRECISION  LOOPC(*), VALUE

C## S T A T U S:
C               SINGLE/DOUBLE CONVERSION: NEEDED (SEE CONVRT).
C
C               IGNORE LINES BEGINNING WITH  "C!!!!" .
C
C               THIS VERSION IS IN   S I N G L E   PRECISION.
C!!!!           THIS VERSION IS IN   D O U B L E   PRECISION.
C
C               SYSTEM  DEPENDENCE:                      NONE.
C
C>RCS $HEADER: LPCK.F,V 1.10 91/11/20 10:53:02 BUCKLEY EXP $
C>RCS $LOG:     LPCK.F,V $
C>RCS REVISION 1.10  91/11/20  10:53:02  BUCKLEY
C>RCS FINAL SUBMISSION TO TOMS
C>RCS
C>RCS REVISION 1.9  89/06/30  13:39:46  BUCKLEY
C>RCS PREPARING SUBMITTED VERSION OF MT
C>RCS
C>RCS REVISION 1.3.1.1  89/05/20  16:42:54  BUCKLEY
C>RCS TEMP. TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.3  89/05/18  12:20:46  BUCKLEY
C>RCS FINAL TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.2  89/05/15  14:48:05  BUCKLEY
C>RCS INITIAL INSTALLATION OF MT INTO RCS FORM.
C>RCS
C>RCS REVISION 1.1  89/01/17  16:50:11  BUCKLEY
C>RCS INITIAL REVISION
C>RCS
C
C## D E S C R I P T I O N:
C
C           THIS ROUTINE PICKS A VALUE FROM THE LOOP CONTROL ARRAY.
C
C
C      THE DESCRIPTION OF THE LOOP CONTROL STRUCTURE IS GIVEN IN ZZLADV.
C  IN ZZLADV, THE ARRAY LOOPX GIVES THE INDICES IN LOOPC FOR THE VARIOUS
C  POSITIONS OF THE ODOMETER. THE ENTRIES ARE TAKEN AS IN A REGULAR
C  ODOMETER IN THE ORDER FROM RIGHT TO LEFT, NAMELY FROM ENTRIES N,
C  N-1, ... ,1 OF LOOPX.
C
C      HERE WE HAVE A SECOND INDEX ARRAY ORDER AND A POINTER PT. IN THE
C  MAIN PROGRAM THERE ARE A FIXED NUMBER OF QUANTITIES FOR WHICH LISTS
C  OR LOOPS MAY BE SPECIFIED. THEY ARE IN A FIXED ORDER, SAY Q1, Q2,
C  ... , QN. THE ARRAY ORDER SPECIFIES WHICH POSITION IN THE ODOMETER
C  EACH OF THESE CORRESPONDS TO. THUS IF ORDER(1) = 4, THEN THE CURRENT
C  VALUE OF Q1 IS OBTAINED FROM THE 4TH POSITION IN THE ODOMETER. PT
C  SPECIFIES WHICH QUANTITY WE WANT TO SAMPLE FROM THE ODOMETER.
C
C## E N T R Y   P O I N T S: THE NATURAL ENTRY ZZLPCK
C## S U B R O U T I N E S:   NINT ... INTRINSIC
C## P A R A M E T E R S:     NONE ARE DEFINED.
C## L O C A L   D E C L:
                             INTEGER   J

C## S A V E:                 NONE SELECTED.
C## E Q U I V A L E N C E S: NONE ARE DEFINED.
C## C O M M O N:             NONE IS DEFINED.
C## D A T A:                 NONE ARE SET.
C##                                                E X E C U T I O N
C##                                                E X E C U T I O N

      J = LOOPX( ORDER(PT) )

      IF ( NINT ( LOOPC(J) ) .LE. 0 ) THEN
         VALUE = LOOPC(J+1)
      ELSE
         VALUE = LOOPC ( J + NINT(LOOPC(J+1)) + 1 )
      ENDIF
      GOTO 90000

C## E X I T
90000      RETURN

C## F O R M A T S:  NONE ARE DEFINED.
C##                 E N D         OF ZZLPCK.
                    END
