rem Remove archive attribute from all files (recursing into subdirectories)
attrib -a *.*/s
rem Now put back for the ones we want
attrib +a slattrib.bat
attrib +a slpkzip.bat
attrib +a slsetup.bat
attrib +a sltar.bat
attrib +a librarie.dir
attrib +a read.me
attrib +a d02kef\d02kef.doc
attrib +a d02kef\d02kef.for
attrib +a d02kef\d02kef.lnk
attrib +a latex\slref.bib
attrib +a latex\graph1.eps
attrib +a latex\graph2.eps
attrib +a latex\jdpdefs.tex
attrib +a latex\epsf.tex
attrib +a latex\esub2acm.sty
attrib +a latex\sldriver.tex
attrib +a latex\sldriver.bbl
attrib +a latex\sltstalg.tex
attrib +a latex\sltstalg.bbl
attrib +a latex\sltstpak.tex
attrib +a latex\sltstpak.bbl
attrib +a marcopak\marcomod.for
attrib +a marcopak\marcomod.lnk
attrib +a probsets\sample.for
attrib +a probsets\standard.for
attrib +a sldriver\makefile
attrib +a sldriver\samplrun.dat
attrib +a sldriver\samplrun.out
attrib +a sldriver\batchio.for
attrib +a sldriver\dbmod.for
attrib +a sldriver\safeio.for
attrib +a sldriver\slconsts.for
attrib +a sldriver\sldriver.for
attrib +a sldriver\slpset.for
attrib +a sldriver\sltstpak.for
attrib +a sldriver\sltstvar.for
attrib +a sldriver\slutil.for
attrib +a sldriver\solvrs.for
attrib +a sldriver\errflags.hlp
attrib +a sldriver\initpuff.hlp
attrib +a sldriver\slbrows.hlp
attrib +a sldriver\sld02k.hlp
attrib +a sldriver\slhelp0.hlp
attrib +a sldriver\bsample.lnk
attrib +a sldriver\bstandrd.lnk
attrib +a sldriver\sample.lnk
attrib +a sldriver\standard.lnk
attrib +a sldriver\evsimp.for
attrib +a sldriver\evsimp.lnk
attrib +a sldriver\sample\keep.me
attrib +a sldriver\standard\keep.me
attrib +a sldriver\standard\truevals\evtru.01
attrib +a sldriver\standard\truevals\evtru.02
attrib +a sldriver\standard\truevals\evtru.05
attrib +a sldriver\standard\truevals\evtru.07
attrib +a sldriver\standard\truevals\evtru.15
attrib +a sldriver\standard\truevals\evtru.18
attrib +a sldriver\standard\truevals\evtru.19
attrib +a sldriver\standard\truevals\evtru.20
attrib +a sldriver\standard\truevals\evtru.21
attrib +a sldriver\standard\truevals\evtru.22
attrib +a sldriver\standard\truevals\evtru.23
attrib +a sldriver\standard\truevals\evtru.28
attrib +a sldriver\standard\truevals\evtru.29
attrib +a sldriver\standard\truevals\evtru.30
attrib +a sldriver\standard\truevals\evtru.32
attrib +a sldriver\standard\truevals\evtru.34
attrib +a sldriver\standard\truevals\evtru.35
attrib +a sldriver\standard\truevals\evtru.36
attrib +a sldriver\standard\truevals\evtru.40
attrib +a sldriver\standard\truevals\evtru.41
attrib +a sldriver\standard\truevals\evtru.43
attrib +a sldriver\standard\truevals\eftru.01
attrib +a sldriver\standard\truevals\eftru.02
attrib +a sldriver\standard\truevals\eftru.07
attrib +a sldriver\standard\truevals\eftru.15
attrib +a sldriver\standard\truevals\eftru.20
attrib +a sldriver\standard\truevals\eftru.21
attrib +a sldriver\standard\truevals\eftru.22
attrib +a sldriver\standard\truevals\eftru.28
attrib +a sldriver\standard\truevals\eftru.29
attrib +a sldriver\standard\truevals\eftru.35
attrib +a sldriver\standard\truevals\eftru.36
attrib +a sldriver\standard\truevals\eftru.41
attrib +a sldriver\standard\truevals\sdtru.56
attrib +a sldriver\standard\truevals\sdtru.57
attrib +a sledge\sledgemd.for
attrib +a sledge\sledgemd.lnk
attrib +a sleign\sleignmd.for
attrib +a sleign\sleignmd.lnk
attrib +a sleign2\sleig2md.for
attrib +a sleign2\sleig2md.lnk
attrib +a sleign2\extras\sleign2.doc
attrib +a sleign2\extras\drived.for
attrib +a sleign2\extras\makepqwd.for
attrib +a sleign2\extras\sleign2d.for
attrib +a sleign2\extras\xamplesd.for
attrib +a sleign2\extras\sleign2.hlp
attrib +a sleign2\extras\sleign2x.tex
attrib +a sleign2\extras\sleign2.txt
