function br_plotter = sync_axes(br_plotter)

f = fieldnames(br_plotter.axes);


handles = zeros(length(f),1);
for ii = 1:length(f)
	handles(ii) = br_plotter.axes.(f{ii});
end


% camproj('perspective');
camproj('orthographic')
set(handles(1),...
	'CameraPositionMode','manual',...
	'CameraTargetMode','manual',...
	'DataAspectRatioMode','manual');


h = rotate3d;
set(h,'Enable','off')
setAllowAxesRotate(h,handles(1),false); % disable rotating for second plot
set(handles(1),'dataaspectratio',[1 1 1]);


properties_to_link = {...
'CameraPosition','XLim','YLim','ZLim','View',...
		'CameraTarget','CameraViewAngle','PlotBoxAspectRatio','Position',...
		'CameraUpVector',...
		'Box',...
		'DataAspectRatio','Projection',...
		'CameraPositionMode','CameraTargetMode','DataAspectRatioMode'};
	
	
if ishghandle(handles)

		hlink = linkprop(handles,properties_to_link);  %
		setappdata(handles(1),'graphics_linkprop',hlink);
else
	disp('failed to link handles');
end

% set(handles(1),'units','pixels','Position',[180 20 900 720]);

end
%     'CLimMode',...

	
% 	'CLim',...
%     'Color',...
%     'ColorOrder',...
%    'ButtonDownFcn',...


% {};
% % 

%     'ALim',...
%     'ALimMode',...
%     'AmbientLightColor',...
%     
%     'CameraPosition',...
%     'CameraPositionMode',...
%     'CameraTarget',...
%     'CameraTargetMode',...
%     'CameraUpVector',...
%     'CameraUpVectorMode',...
%     'CameraViewAngle',...
%     'CameraViewAngleMode',...,...
%     ...,...,...,...,...,...
%     'DataAspectRatioMode',...,...
%     'FontAngle',...
%     'FontName',...
%     'FontUnits',...
%     'GridLineStyle',...
%     'HitTest',...
%     'Layer',...
%     'LineStyleOrder',...
%     'LineWidth',...
%     'MinorGridLineStyle',...
%     'OuterPosition',...
%     'PlotBoxAspectRatio',...
%     'PlotBoxAspectRatioMode',...
%     
%     
%     'TickDir',...
%     'TickDirMode',...
%     'TickLength',...
%     'Units',...
%     'View',...
%     'XAxisLocation',...
%     'XColor',...
%     'XDir',...
%     'XGrid',...
%     'XLim',...
%     'XLimMode',...
%     'XMinorGrid',...
%     'XMinorTick',...
%     'XScale',...
%     'XTick',...
%     'XTickLabel',...
%     'XTickLabelMode',...,...
%     'XTickMode',...
%     'YAxisLocation',...
%     'YColor',...
%     'YDir',...
%     'YGrid',...
%     'YLim',...,...
%     'YLimMode',...
%     'YMinorGrid',...
%     'YMinorTick',...
%     'YScale',...
%     'YTick',...
%     'YTickLabel',...
%     'YTickLabelMode',...
%     'YTickMode',...
%     'ZColor',...
%     'ZDir',...
%     'ZGrid',...
%     'ZLim',...
%     'ZLimMode',...
%     'ZMinorGrid',...
%     'ZMinorTick',...
%     'ZScale',...
%     'ZTick',...
%     'ZTickLabel',...
%     'ZTickLabelMode',...
%     'ZTickMode',...