      SUBROUTINE ZZSTX0 ( IX0, X0, N, FACTOR, TMP, ARGS )

C## A R G U M E N T S:
                      INTEGER           IX0,    N
                      DOUBLE PRECISION  X0(N), FACTOR, TMP(N), ARGS(*)
C!!!!                 REAL              X0(N), FACTOR, TMP(N), ARGS(*)
C## S T A T U S:
C               IGNORE LINES BEGINNING WITH  "C!!!!" .
C
C               SYSTEM  DEPENDENCE:                      NONE.
C               SINGLE/DOUBLE CONVERSION: NEEDED (SEE CONVRT).
C
C               THIS VERSION IS IN   D O U B L E   PRECISION.
C!!!!           THIS VERSION IS IN   S I N G L E   PRECISION.

C>RCS $HEADER: STX0.F,V 2.2 91/11/20 10:53:10 BUCKLEY EXP $
C>RCS $LOG:     STX0.F,V $
C>RCS REVISION 2.2  91/11/20  10:53:10  BUCKLEY
C>RCS FINAL SUBMISSION TO TOMS
C>RCS
C>RCS REVISION 2.1  90/07/31  11:55:20  BUCKLEY
C>RCS REMOVED UNUSED VAR.
C>RCS
C>RCS REVISION 2.0  90/07/31  11:35:15  BUCKLEY
C>RCS MINOR MOD TO USE BLAS
C>RCS
C>RCS REVISION 1.9  89/06/30  13:41:36  BUCKLEY
C>RCS PREPARING SUBMITTED VERSION OF MT
C>RCS
C>RCS REVISION 1.1  89/01/17  16:50:14  BUCKLEY
C>RCS INITIAL REVISION
C>RCS
C## D E S C R I P T I O N:
C
C    COMPUTE STANDARD STARTING POINTS FOR TEST FUNCTIONS AND PUT INTO
C    X0.  THE STARTING POINT IS DEFINED ACCORDING TO THE CODE IX0.
C    SEE THE ROUTINE ZZVECT.
C
C      IF IX0 = 0, X0(I) ARE DEFINED ON ENTRY FOR I=1,...,N.
C                ( THIS IS EQUIVALENT TO SPECIFYING IX0 = N. )
C      IF IX0 > 0, A CYCLE IS DEFINED AND MUST BE EXPANDED.
C      IF IX0 < 0  ON ENTRY, THEN A SELECTED FORMULA IS USED TO
C                  COMPUTE VALUES FOR THE COMPONENTS OF X0.
C
C    IN ANY CASE, ONCE THE VALUES FOR X0 ARE ESTABLISHED, ALL
C    COMPONENTS OF X0 ARE THEN MULTIPLIED BY FACTOR (UNLESS OF
C    COURSE FACTOR = 1).
C
C## E N T R Y   P O I N T S: THE NATURAL ENTRY ZZSTX0.
C## S U B R O U T I N E S:   ZZVECT.
C## P A R A M E T E R S:
      DOUBLE PRECISION  ZERO,       ONE,       TWO,       THREE
C!!!! REAL              ZERO,       ONE,       TWO,       THREE
      PARAMETER (       ZERO = 0D0, ONE = 1D0, TWO = 2D0, THREE = 3D0)

      DOUBLE PRECISION  FOUR,       FIVE,      SIX,       SEVEN
C!!!! REAL              FOUR,       FIVE,      SIX,       SEVEN
      PARAMETER (       FOUR = 4D0, FIVE = 5D0,SIX = 6D0, SEVEN = 7D0)

      DOUBLE PRECISION  EIGHT,         NINE,          TEN
C!!!! REAL              EIGHT,         NINE,          TEN
      PARAMETER (       EIGHT = 8D0,   NINE = 9D0,    TEN = 10D0     )

C## L O C A L   D E C L:     NONE ARE DEFINED.
C## S A V E:                 NONE SELECTED.
C## E Q U I V A L E N C E S: NONE ARE DEFINED.
C## C O M M O N:             NONE IS DEFINED.
C## D A T A:                 NO DATA VALUES SET.

C## E X E C U T I O N
C## E X E C U T I O N

      CALL ZZVECT ( IX0, N, TMP, X0, ARGS )

C-----NOW APPLY FACTOR TO THE STARTING POINT.

      IF ( FACTOR .NE. ONE ) THEN

         CALL ZZSCAL ( N, FACTOR, X0, 1 )

      ENDIF
      GOTO 90000

C## E X I T
90000      RETURN

C## F O R M A T S:  NONE ARE DEFINED.
C##                 E N D         OF ZZSTX0.
                    END
