      INTEGER FUNCTION ZZLFTI (STRING, N )

C## A R G U M E N T S:
                        INTEGER N
                        CHARACTER *(*) STRING
C## S T A T U S:
C
C               SYSTEM  DEPENDENCE:                      NONE.
C               SINGLE/DOUBLE CONVERSION:        NOT REQUIRED.
C
C>RCS $HEADER: LFTI.F,V 1.10 91/11/19 16:13:35 BUCKLEY EXP $
C>RCS $LOG:     LFTI.F,V $
C>RCS REVISION 1.10  91/11/19  16:13:35  BUCKLEY
C>RCS FINAL SUBMISSION TO TOMS
C>RCS
C>RCS REVISION 1.9  89/06/30  13:28:59  BUCKLEY
C>RCS PREPARING SUBMITTED VERSION OF MT
C>RCS
C>RCS REVISION 1.3.1.1  89/05/20  13:39:35  BUCKLEY
C>RCS TEMP. TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.3  89/05/18  14:26:47  BUCKLEY
C>RCS FINAL TEST OF MT BEFORE SUBMITTING
C>RCS
C>RCS REVISION 1.2  89/05/15  14:44:35  BUCKLEY
C>RCS INITIAL INSTALLATION OF MT INTO RCS FORM.
C>RCS

C## D E S C R I P T I O N:

C     THIS ROUTINE TAKES THE INTEGER N, CONVERTS IT TO A CHARACTER
C     REPRESENTATION, AND PUTS IT INTO STRING WITH NO LEADING
C     BLANKS. IT RETURNS THE LENGTH OF THE RESULTING STRING WITH
C     TRAILING BLANKS NOT INCLUDED.

C## E N T R Y   P O I N T S: THE NATURAL ENTRY ZZLFTI.
C## S U B R O U T I N E S:   ZZLEFT.
C## P A R A M E T E R S:     NONE ARE DEFINED.
C## L O C A L   D E C L:
                             INTEGER ZZLEFT

C## S A V E:                 NONE SELECTED.
C## E Q U I V A L E N C E S: NONE ARE DEFINED.
C## C O M M O N:             NONE IS DEFINED.
C## D A T A:                 NO DATA VALUES SET.

C##                                                  E X E C U T I O N
C##                                                  E X E C U T I O N
                        WRITE ( STRING, '(I10)' ) N
                        ZZLFTI = ZZLEFT(STRING)
C## E X I T
90000      RETURN

C## F O R M A T S:  NONE ARE DEFINED.
C##                 E N D         OF ZZLFTI.
                    END
