#!/usr/bin/csh
#PBS -l nodes=16:whirlwind:ppn=1 -l walltime=15:00
exec pbslam -W /sciclone/home10/ancher/pcdm-1.0 $PBS_O_WORKDIR/pcdm $PBS_O_WORKDIR/models/flow4000_madd.dat $PBS_O_WORKDIR/models/flow4000_madd.cdt -a 1.359375e-05 -m 512 -s /sciclone/home10/ancher/pcdm-1.0/statistics/aggr_512/flow4000_madd/16
