% problem.string.m
fprintf('\n====================================================================================\n')
fprintf('\n               >>>   Example 5 - Talbot Suite DE   <<<\n')
fprintf('\n         Application of Talbot''s method to solve the PDE equation\n')
fprintf('\n\t\t\tu_t (x,y,t) = u_xx (x,y,t) + u_yy (x,y,t),      0 < x,y < 1,  t>0\n')
fprintf('\n\twith conditions:')
fprintf('\n\t\t\tu(x,y,0+) = x*(x-1) + y*(y-1)')
fprintf('\n\t\t\tu(0,y,t) = u(1,y,t) = 4*t + y*(y-1)')
fprintf('\n\t\t\tu(x,0,t) = u(x,1,t) = 4*t + x*(x-1)\n')
fprintf('\n\tThe analytical solution is\n\n')
fprintf('\t\tu(x,y,t) = 4*t + x*(x-1) + y*(y-1)\n')
fprintf('\n\tand its Laplace Transform is\n\n')
fprintf('\t\t          4    x*(x-1) + y*(y-1)\n')
fprintf('\t\tU(x,s) = --- + -----------------\n')
fprintf('\t\t         s^2           s\n')
fprintf('\n\twith a double pole at 0\n')
fprintf('\n\t     and abscissa of convergence: sigma0 = 0\n')
fprintf('\n====================================================================================\n')
