char *str = "\n====================================================================================\n"
            "\n               >>>   Example 1b - Talbot Suite DE   <<<\n"
            "\n         Application of Talbot's method to solve the PDE equation\n"
            "\n\t\t\tu_t (x,t) = u_x (x,t),         x > X0,  t>0\n"
            "\n\twith conditions:"
            "\n\t\t\tu(x,0+) = x*sin(3*x)/6"
            "\n\t\t\tu(X0,t) = (X0+t)*sin(3*(X0+t))/6\n\n"
            "\n\tThe analytical solution is\n\n"
            "\t\tu(x,t) = (x+t)*sin(3*(x+t))/6\n"
            "\n\tand its Laplace Transform is\n\n"
            "\t\t         (s*x+1)*sin(3*x)+3*x*cos(3*x)   s*cos(3*x)-3*sin(3*x)\n"
            "\t\tU(x,s) = ----------------------------- + ---------------------\n"
            "\t\t                   6*(s^2+9)                   (s^2+9)^2\n"
            "\n\twith double poles at +/-3i\n"
            "\n\t     and abscissa of convergence: sigma0 = 0\n"
            "\n====================================================================================\n";
