
#================ Data input ===================

library(lubridate)
filename="./purchases.csv";

#if CSV file was generated by Excel
MyData <- read.csv(file=filename, header=TRUE, sep=";", stringsAsFactors = FALSE, dec=",")
t=as.numeric(dmy(MyData[[1]]))
#t=as.numeric((MyData[[1]]))

#if CSV file was generated by R
#MyData <- read.csv(file=filename, header=TRUE, sep=",", stringsAsFactors = FALSE, dec=".")
#t=as.numeric(ymd(MyData[[1]]))

t=t[!is.na(t)]
n=length(t)
Y=MyData[[2]]
Y=Y[1:(n-1)] # Last value not used

#origin=dmy(MyData[[1]][1])-t[1] #will need time origin for x-axis labes
#origin=ymd(MyData[[1]][1])-t[1]  
#=========== Calculating spline =============
m=round(n)
x=seq(t[1],t[n],1)
#s=t
s=seq(t[1],t[n],length=m)

#W=rep(1,n-1)
#W[1]=0.5
#W[10]=0.1
#alpha=10^5



# { time1=proc.time()
y=int_spline(t,Y,s=s,alpha=10^5)

#time_dif=proc.time()-time1}
#time_dif
#================ Plotting spline with graph of average values ==================

#for graph of average values
x2=NULL
y2=NULL
 for (i in 1:(n-1))
 {
   x2=c(x2,t[i],t[i+1])
   y2=c(y2,Y[i]/(t[i+1]-t[i]),Y[i]/(t[i+1]-t[i]))
 }



plot(x,y,col="red",type="l",lwd="1",lty=1, xaxt="n",ylim=range(c(y,y2)),xlim=range(c(x,x2)))
axis.Date(1, at=seq(min(dmy(MyData[[1]])), max(dmy(MyData[[1]])), by="months"),format="%m-%Y")
#axis(1, at=t,labels=as_date(t,origin))    # labels coincide with observations
#axis(1, at=t,labels=MyData[[1]])
lines(x2,y2,col="black",type="l",lwd="2",lty=1)

#================ Data output ===================
#write to the csv file

#MyWriteData=data.frame(x+origin,y)
#s2="F:/FilePath/f_spline_out.csv";
#write.csv(MyWriteData, file = s2,row.names=FALSE)


#================ Integral function F(t) ===================

# r=int_spline(t,Y,m=m,alpha=10^5,info=TRUE)
# s=r$s
# h=r$h
# g=r$g
# g2=r$gamma
# 
# Fy=rep(0,length(x))
# 
# N=1; #index of interval
# Fn=0;
# for (j in (1:length(x)))
# {
#   while (x[j]<t[n] & x[j]>=s[N]+h[N])
#     {
#       Fn=Fn+h[N]*(g[N+1]+g[N])/2 - h[N]^3*(g2[N+1]+g2[N])/24
#       N=N+1;
#     }
#   Fy[j] = Fn + (x[j]-s[N])^2/h[N]/2*g[N+1]   + (h[N]^2-(s[N+1]-x[j])^2)/h[N]/2*g[N]    + (x[j]-s[N])^2*((x[j]-s[N])^2-2*(h[N]^2))/h[N]/24*g2[N+1]   - (x[j]-s[N])^2*(s[N+1]-x[j]+h[N])^2/h[N]/24*g2[N]
# }
# xrange=range(x)
# yrange=range(Fy)
# plot(x,Fy,col="red",type="l",lwd="1",lty=1, xaxt="n",ylim=yrange,xlim=xrange)
# #axis.Date(1, at=seq(min(dmy(MyData[[1]])), max(dmy(MyData[[1]])), by="months"),format="%m-%Y")
# #axis(1, at=t)
# axis(1, at=t,labels=MyData[[1]])
