MODULE types
use blas_sparse_namedconstants
! **********************************************************************
!     Author : Christof Voemel
!
!     Date of last modification : 05.12.00
!      
!     Description : CONTAINS THE BASIC TYPES FOR SPARSE MATRICES/VECTORS
! **********************************************************************

TYPE ISPMAT
INTEGER :: M,K
CHARACTER*5 :: FIDA
CHARACTER*11 :: DESCRA
INTEGER, DIMENSION(10) :: INFOA
INTEGER, POINTER, DIMENSION(:) :: A
INTEGER, POINTER, DIMENSION(:) :: IA1,IA2,PB,PE,BP1,BP2
END TYPE ISPMAT

TYPE DSPMAT
INTEGER :: M,K
CHARACTER*5 :: FIDA
CHARACTER*11 :: DESCRA
INTEGER, DIMENSION(10) :: INFOA
REAL(KIND=dp), POINTER, DIMENSION(:) :: A
INTEGER, POINTER, DIMENSION(:) :: IA1,IA2,PB,PE,BP1,BP2
END TYPE DSPMAT

TYPE SSPMAT
INTEGER :: M,K
CHARACTER*5 :: FIDA
CHARACTER*11 :: DESCRA
INTEGER, DIMENSION(10) :: INFOA
REAL(KIND=sp), POINTER, DIMENSION(:) :: A
INTEGER, POINTER, DIMENSION(:) :: IA1,IA2,PB,PE,BP1,BP2
END TYPE SSPMAT

TYPE CSPMAT
INTEGER :: M,K
CHARACTER*5 :: FIDA
CHARACTER*11 :: DESCRA
INTEGER, DIMENSION(10) :: INFOA
COMPLEX(KIND=sp), POINTER, DIMENSION(:) :: A
INTEGER, POINTER, DIMENSION(:) :: IA1,IA2,PB,PE,BP1,BP2
END TYPE CSPMAT

TYPE ZSPMAT
INTEGER :: M,K
CHARACTER*5 :: FIDA
CHARACTER*11 :: DESCRA
INTEGER, DIMENSION(10) :: INFOA
COMPLEX(KIND=dp), POINTER, DIMENSION(:) :: A
INTEGER, POINTER, DIMENSION(:) :: IA1,IA2,PB,PE,BP1,BP2
END TYPE ZSPMAT

END MODULE types
